### ISSUE TITLE
Gegevens uit de WHOIS API

### ISSUE THREAD

**Issue by tom-2810** [IvarSchuyt/connect-your-tribe-profile-card#3]
Je kan via het admin paneel van de WHOIS API https://whois.fdnd.nl/admin je gegevens kunnen invullen. Door middel van node kan je bijvoorbeeld je naam weer ophalen met `<%= member.name %>` in het ejs bestand. Dan zal je wel eerst de data moeten meegeven via het js bestand. Hieronder staat het voorbeeld van de workshop.

<img width="733" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/112861614/218052888-a762400a-e3a7-4522-96c0-a73f631d9c72.png">

<img width="1094" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/112861614/218052923-fdc863aa-d976-4f4c-ac78-10538eba1d83.png">

**Comment by IvarSchuyt** [comment]
Done, thanks!
